[nfs]
172.31.41.242 ansible_ssh_user='ec2-user'

[webservers]
172.31.34.77 ansible_ssh_user='ec2-user'
172.31.44.116 ansible_ssh_user='ec2-user'

[db]
172.31.16.201 ansible_ssh_user='ec2-user' 

[lb]
172.31.41.90 ansible_ssh_user='ubuntu'